### PR TITLE
Enable network access

### PR DESCRIPTION
**Pull request by Kekun**
https://github.com/flathub/com.github.fabiocolacio.marker/issues/13

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by jsparber** [comment]
I opened an issue for Marker about this: https://github.com/fabiocolacio/Marker/issues/231

**Comment by jsparber** [comment]
I fixed the issue upstream
https://github.com/fabiocolacio/Marker/pull/246

**Comment by pfinnigan** [comment]
I installed Marker today on Fedora 30. I used the stable release and got version 2018.07.03 which still contains this bug 12 months later.

**Pull request closed without merging**
